version: "3"

services:
  # UI is available: http://localhost:8091/ui/index.html
  couchbase:
    container_name: couchbase
    image: couchbase:community-7.1.1
    volumes:
      - couchbase_data:/opt/couchbase/var
    networks:
      - couchbase-net
    ports:
      - 8091-8093:8091-8093
      - 11210:11210

volumes:
  couchbase_data:
    driver: local

networks:
  couchbase-net:
