logging:
  level:
    com.couchbase: INFO
    # To log generated Nickel queries
    org.springframework.data.couchbase.repository.query: TRACE
    org.springframework.data.couchbase.core: TRACE

server:
  port: 8081

spring:
  couchbase:
    connection-string: "couchbase://127.0.0.1"
    username: "admin"
    password: "password"
    bucket: "couchbase_course_bucket"
