package hu.ptomi.course.couchbase.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.couchbase.core.mapping.Document;
import org.springframework.data.couchbase.core.mapping.Field;
import org.springframework.data.couchbase.repository.Collection;
import org.springframework.data.couchbase.repository.Scope;

import java.util.List;

@Document
@Scope(value = "projects")
@Collection(value = "project")
public record Project(
        @Id String id,
        String name,
        String code,
        @Field("desc") String description,
        String startDate,
        String endDate,
        @Field("cost") long estimatedCost,
        List<String> countryList,
        // Version is generated by the db.
        @Version long version
) {
}
